admins = [1554899129,1400449333]

Text_userAlreadyOpenConv="You have already opened a conversation in our system, please be patient"
Text_userWarnBan = "Stop spamming❌. {attempt} more attempts will get you banned "
Text_userStart = "Welcome {fname}\nPlease feel free to ask any question.\nWe will assist you as soon as we can."
Text_usesSuccessCall = "We have recieved your message, and will respond as soon as we can.\nIn the meanwhile, please make sure to include any additional details that might help us in answering your question.\nYour track id is `{mid}`"
Text_userAleradyHaveOpenCall = "You are already in our members, please ask your question."
Text_newCallMessage = "from [{type}](tg://user?id={uid}) [{time}] \n{text}\n"
######################### AMDIN:
Text_logAdminMain = "🤖REPORT🤖\n [{typeUser}](tg://user?id={uid}) [{time}] \n{text}"
Text_logAdmin = "🤖[{time}] \n{text}"
Text_CallAlreadyOpen = "This call is already openned by another [Admin](tg://user?id={uid})"
Text_adminStart = "Hello {name} , \n select /ready button for responding the earliest calls\n /help /cmds"
Text_adminOpenConv = "[🔮🔮🔮🔮[{name}](tg://user?id={uid}) accepted the call🔮🔮🔮🔮][{time}]\n{message}\n"
Text_callPickedAdmin = "You have picked the call and user will recive your messages "
Text_AdminConvToUser = "[{name}](tg://user?id={uid}): \n {text}"
Text_HelpCmd = "__LIST OF AVAILABLE COMMANDS FOR Operators__\n/ban [uid] #To ban a user\n/unban [uid] #To unban a user\n/getUser [uid] #Get user by it's peer_id\n/getUID [username/me] #Get peer_id of a user. Use __me__ to get peer_id of yourself\n/getPhoto [fileId] #Get image/file by file_id\n/showDb #Debug purposes. shows the prints the calls in console\n/cmds __or__ /help #To get list of available commands\n\n__NOTE__\nAdmins can only send `'Gifs'` and `'Photos'` through this robot. Other types of media or documents will not be send to the user. \n__dont waste your time uploading huge files__"
Text_FileInvalid = "Your message contains invalid files.\nonly GIF and photos are allowed"
Keyboard_Accept = "/accept {id} #open the conversation"
Keyboard_Cancel = "/skip #skip the conversation , this will lay it so other operators can open it."
Keyboard_CReset = "/creset #re-open the skipped conversation"
Keyboard_Close = "/cancel #close the conversation , other operators would not be able to open this call anymore"
Keyboard_Next = "/next {id} #go to the next call"
Keyboard_Ready = "/ready #get conversations."
Keyboard_CMDS = f"/cmds #get list of admin\operator commands."